import re
import tomllib
from pathlib import Path

import click

from .logger import logger
from .xdg import get_config_dir


def load_config(config_path=None):
    if config_path:
        paths = [Path(config_path).expanduser().resolve()]
    else:
        # XDG-compliant pathing prioritized
        config_dir = get_config_dir()
        paths = [
            Path.cwd() / ".breakfast.toml",
            config_dir / "config.toml",
            Path.home() / ".breakfast.toml",
        ]

    merged = {}
    for path in reversed(paths):
        if path.exists():
            with open(path, "rb") as f:
                try:
                    data = tomllib.load(f)
                except Exception as e:
                    logger.warning("config_parse_error path=%s error=%r", path, str(e))
                    msg = f"Warning: Failed to parse config {path}: {e}"
                    click.echo(click.style(msg, fg="yellow"), err=True)
                    continue
            for key, value in data.items():
                if isinstance(value, list) and isinstance(merged.get(key), list):
                    merged[key] = value + merged[key]
                else:
                    merged[key] = value
    return merged


def generate_default_config():
    """Generate a default XDG-compliant config file."""
    config_dir = get_config_dir()
    config_path = config_dir / "config.toml"
    if config_path.exists():
        click.echo(
            click.style(f"Config file already exists at {config_path}", fg="yellow")
        )
        return False

    config_path.parent.mkdir(parents=True, exist_ok=True)
    default_content = """\
# =============================================================================
#  breakfast configuration file
#  Generated by: breakfast --init-config
#
#  All options are commented out — uncomment and edit to activate.
#  Options set here act as persistent defaults; CLI flags always take
#  precedence over config file values for a single run.
#
#  Config file locations (highest → lowest priority):
#    ./.breakfast.toml            (current directory)
#    ~/.config/breakfast/config.toml   (XDG default, this file)
#    ~/.breakfast.toml
# =============================================================================


# -----------------------------------------------------------------------------
# Target
# Which organisation and repos to query by default.
# -----------------------------------------------------------------------------

# GitHub organisation to query for open pull requests.
# Equivalent to: breakfast -o <value>
# Required (must be set here or passed with -o on every run).
# organization = "my-org"

# Filter repositories by name substring. Only repos whose name contains
# this string are included. An empty string matches all repos.
# Equivalent to: breakfast -r <value>
# repo-filter = "my-app"


# -----------------------------------------------------------------------------
# Filtering
# Control which PRs appear in the output.
# -----------------------------------------------------------------------------

# Authors to exclude from the output (case-insensitive). Useful for hiding
# bot PRs. List format — add as many entries as you like.
# Equivalent to: --ignore-author dependabot[bot] --ignore-author renovate[bot]
# ignore-author = ["dependabot[bot]", "renovate[bot]"]

# Show only PRs authored by the currently authenticated GitHub user
# (determined from GITHUB_TOKEN). Useful for a personal morning view.
# Equivalent to: --mine-only
# mine-only = false

# Maximum number of PRs to display. Applied after all other filters.
# Unset means show all results.
# Equivalent to: --limit <n>
# limit = 25


# -----------------------------------------------------------------------------
# Columns
# Toggle and configure optional table columns.
# -----------------------------------------------------------------------------

# Show a column with the PR age in days (time since it was opened).
# Values are colour-coded: green < 10d, yellow < 20d, orange < 50d, red 50d+.
# Equivalent to: --age
# age = false

# Show a column with the CI/check status for each PR. Requires an extra
# API call per PR so is opt-in. Values: pass, fail, pending, none.
# Equivalent to: --checks
# checks = false

# Show a column with the review approval status for each PR. Requires an
# extra API call per PR so is opt-in. Values: approved, pending, changes.
# Equivalent to: --approvals
# approvals = false

# Truncate PR titles to this many characters (appends … when truncated).
# Useful on narrow terminals. Unset means no truncation.
# Equivalent to: --max-title-length <n>
# max-title-length = 72


# -----------------------------------------------------------------------------
# Display
# Control how the output looks.
# -----------------------------------------------------------------------------

# Output format. "table" renders a coloured terminal table (default).
# "json" outputs machine-readable JSON — useful for scripting or piping.
# Equivalent to: --json
# format = "table"

# How status columns (Checks, Approved, Mergeable?) are rendered.
#   emoji  — colourful emoji labels, e.g. ✅ pass, ❌ fail  (default)
#   ascii  — plain text fallback, e.g. pass, fail — safe for all terminals
# Equivalent to: --status-style emoji|ascii
# status-style = "emoji"


# -----------------------------------------------------------------------------
# Legendary PRs ⚔️
# Surface PRs that have become a team institution.
# A PR is legendary when it has 100+ total comments AND has been open 30+ days.
# -----------------------------------------------------------------------------

# Append ⚔️ to the State column of legendary PRs so they stand out at a glance.
# Equivalent to: --legendary
# legendary = false

# Show ONLY legendary PRs, hiding everything else. Implies legendary = true.
# Equivalent to: --legendary-only
# legendary-only = false


# -----------------------------------------------------------------------------
# Caching
# Cache results on disk so repeated runs are near-instant.
# The cache is keyed by (organization, repo-filter) — each pair gets its own
# file stored in ~/.cache/breakfast/ (or $XDG_CACHE_HOME/breakfast/).
# -----------------------------------------------------------------------------

# Enable the disk cache. Off by default.
# Use --refresh or --refresh-prs on a cached run to force a fresh fetch.
# Equivalent to: --cache
# cache = false

# How long cached results stay fresh before the next run fetches again.
# Accepts seconds (e.g. 300) or a human-friendly suffix: 30s, 5m, 2h.
# Only relevant when cache = true.
# Equivalent to: --cache-ttl <value>
# cache-ttl = "5m"

# Exclude draft PRs from results
# no-drafts = true


# -----------------------------------------------------------------------------
# Performance
# Control how aggressively breakfast fetches data in parallel.
# -----------------------------------------------------------------------------

# Number of parallel workers used to fetch PR details, check statuses, and
# approval statuses. Higher values fetch faster but consume more API rate limit.
# Equivalent to: --workers <n>
# workers = 64


# -----------------------------------------------------------------------------
# Diagnostics
# Tools for understanding what breakfast is doing under the hood.
# -----------------------------------------------------------------------------

# Print API diagnostics to stderr after output: total elapsed time, number of
# REST and GraphQL calls made, and rate-limit remaining/reset info.
# Equivalent to: --debug
# debug = false
"""
    config_path.write_text(default_content)
    click.echo(click.style(f"Created default config at {config_path}", fg="green"))
    return True


def normalize_ignore_authors(ignore_authors):
    if not ignore_authors:
        return set()
    return {
        author.strip().lower() for author in ignore_authors if author and author.strip()
    }


def filter_pr_details(
    pr_details,
    ignore_authors,
    mine_only=False,
    current_user_login=None,
    no_drafts=False,
    drafts_only=False,
    filter_state=None,
    filter_check=None,
    filter_approval=None,
    check_statuses=None,
    approval_statuses=None,
    search_title=None,
):
    ignore_set = normalize_ignore_authors(ignore_authors)
    current_user_login_normalized = (
        current_user_login.lower()
        if mine_only and current_user_login and current_user_login.strip()
        else None
    )
    filtered = []
    for pr_detail in pr_details:
        author_login = pr_detail.get("user", {}).get("login", "")
        author_login_normalized = author_login.lower()

        if author_login_normalized in ignore_set:
            continue
        if (
            current_user_login_normalized
            and author_login_normalized != current_user_login_normalized
        ):
            continue
        is_draft = pr_detail.get("draft", False)
        if no_drafts and is_draft:
            continue
        if drafts_only and not is_draft:
            continue
        if filter_state and pr_detail.get("state", "").lower() not in {
            s.lower() for s in filter_state
        }:
            continue
        if filter_check and check_statuses is not None:
            pr_check = check_statuses.get(pr_detail["id"], "none")
            if pr_check not in filter_check:
                continue
        if filter_approval and approval_statuses is not None:
            pr_approval = approval_statuses.get(pr_detail["id"], "pending")
            if pr_approval not in filter_approval:
                continue
        if search_title is not None:
            title = pr_detail.get("title", "")
            if not re.search(search_title, title, re.IGNORECASE):
                continue

        filtered.append(pr_detail)
    return filtered
