import re
import tomllib
from datetime import datetime
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as pkg_version
from pathlib import Path

import click

from .api import get_pr_age_days, get_pr_inactive_days
from .logger import logger
from .xdg import get_config_dir, get_config_paths

_DEFAULT_CONFIG_CONTENT = """\
# =============================================================================
#  breakfast configuration file
#  Generated by: breakfast --init-config
#
#  All options are commented out — uncomment and edit to activate.
#  Options set here act as persistent defaults; CLI flags always take
#  precedence over config file values for a single run.
#
#  Config file locations (highest → lowest priority):
#    ./.breakfast.toml            (current directory)
#    ~/.config/breakfast/config.toml   (XDG default, this file)
#    ~/.breakfast.toml
# =============================================================================


# -----------------------------------------------------------------------------
# Target
# Which owner and repos to query by default.
# -----------------------------------------------------------------------------

# GitHub owner (organization or personal account) to query for open pull requests.
# Equivalent to: breakfast -o <value> (repeat -o for multiple owners).
# Required (must be set here or passed with -o on every run).
# For multiple owners, use a list: owner = ["my-org", "another-org"]
# Note: the old 'organization' key still works but is deprecated — use 'owner'.
# owner = "my-org"

# Filter repositories by name. Only repos whose name matches are included.
# Supports substring matching and glob patterns (* ? [). Use a list to match
# any of several filters (OR logic). Omit to match all repos.
# Equivalent to: breakfast -r <value> (repeat -r for multiple filters).
# Single filter:   repo-filter = "my-app"
# Multiple:        repo-filter = ["api", "platform", "service-*"]
# repo-filter = "my-app"


# -----------------------------------------------------------------------------
# Filtering
# Control which PRs appear in the output.
# -----------------------------------------------------------------------------

# Which PR states to fetch from GitHub. Default: open.
# Choices: open, closed, merged, all.
# Equivalent to: --fetch-state <value>
# fetch-state = "open"

# Repositories to exclude from results. Supports glob patterns (same syntax as
# --repo-filter). Useful for hiding archived repos, forks, or internal tooling.
# Equivalent to: --exclude-repo "old-*" --exclude-repo "infra-*"
# exclude-repos = ["old-*", "infra-*"]

# Authors to exclude from the output (case-insensitive). Useful for hiding
# bot PRs. List format — add as many entries as you like.
# Equivalent to: --ignore-author dependabot[bot] --ignore-author renovate[bot]
# ignore-author = ["dependabot[bot]", "renovate[bot]"]

# Show only PRs authored by the currently authenticated GitHub user
# (determined from GITHUB_TOKEN). Useful for a personal morning view.
# Equivalent to: --mine-only
# mine-only = false

# Maximum number of PRs to display. Applied after all other filters.
# Unset means show all results.
# Equivalent to: --limit <n>
# limit = 25


# -----------------------------------------------------------------------------
# Columns
# Toggle and configure optional table columns.
# -----------------------------------------------------------------------------

# Show a column with the PR age in days (time since it was opened).
# Values are colour-coded: green < 10d, yellow < 20d, orange < 50d, red 50d+.
# Equivalent to: --age
# age = false

# Show a column with the CI/check status for each PR. Requires an extra
# API call per PR so is opt-in. Values: pass, fail, pending, none.
# Equivalent to: --checks
# checks = false

# Show a column with the review approval status for each PR. Requires an
# extra API call per PR so is opt-in. Values: approved, pending, changes.
# Equivalent to: --approvals
# approvals = false

# Show a column with the source branch the PR was raised from (e.g. feature/my-thing).
# Rendered as a clickable hyperlink to the branch on GitHub.
# Equivalent to: --head-branch
# head-branch = false

# Show a column with the target branch the PR merges into (e.g. main).
# Rendered as a clickable hyperlink to the branch on GitHub.
# Equivalent to: --base-branch
# base-branch = false

# Show a column with the requested reviewers for each PR.
# Equivalent to: --reviewers
# reviewers = false

# Show a column with the labels for each PR.
# Equivalent to: --show-labels
# show-labels = false

# Truncate PR titles to this many characters (appends … when truncated).
# Useful on narrow terminals. Unset means no truncation.
# Equivalent to: --max-title-length <n>
# max-title-length = 72

# Control which columns appear, their order, headers, and alignment.
# Each entry is {name = "..."} with optional header = "..." and align = "...".
# Optional columns (age, checks, approvals, head-branch, base-branch,
# reviewers, labels) are automatically enabled when included — no need to
# set their individual flags.
# Available names: org, repo, title, author, state, files, commits, diff,
#   comments, age, checks, approvals, head-branch, base-branch, reviewers,
#   labels, mergeable, link
# Expand to multi-line in your config for readability:
#   columns = [
#     {name = "repo"},
#     {name = "title", header = "PR"},
#     {name = "age", align = "right"},
#     {name = "link"},
#   ]
# columns = [{name = "repo"}, {name = "title"}, {name = "author"}, {name = "link"}]


# -----------------------------------------------------------------------------
# Display
# Control how the output looks.
# -----------------------------------------------------------------------------

# Output format. "table" renders a coloured terminal table (default).
# "json" outputs machine-readable JSON — useful for scripting or piping.
# "markdown" renders a GitHub-flavoured Markdown table — great for pasting into docs.
# "csv" outputs comma-separated values for spreadsheet import.
# "template" renders each PR using a custom format string (see template below).
# Equivalent to: --format table|json|markdown|csv|template
# format = "table"

# Custom format string for --format template.
# Available fields: {repo}, {title}, {author}, {url}, {state}, {number},
#   {created_at}, {updated_at}, {additions}, {deletions}, {changed_files},
#   {commits}, {review_comments}, {labels}, {requested_reviewers}
# Equivalent to: --template <value>
# template = "{repo}: {title} ({url})"

# How status columns (Checks, Approved, Mergeable?) are rendered.
#   emoji  — colourful emoji labels, e.g. ✅ pass, ❌ fail  (default)
#   ascii  — plain text fallback, e.g. pass, fail — safe for all terminals
# Equivalent to: --status-style emoji|ascii
# status-style = "emoji"

# A little something extra for the observant. 🌟
# seasonal-colours = true

# Which cultural holiday calendar drives seasonal colours.
#   east-asian — Lunar New Year 🧧, Mid-Autumn Festival 🎑, Songkran 💦, Hanami 🌸
#   hindu      — Diwali 🪔, Holi 🎨
#   islamic    — Eid al-Fitr 🌙, Eid al-Adha 🐑
#   jewish     — Hanukkah 🕎, Passover 🪬, Rosh Hashanah 🍎, Sukkot 🌿
#   sikh       — Vaisakhi 🌾, Bandi Chhor Divas 🪔
#   western    — Christmas 🎄, Easter 🐣, Pride Month 🌈, Halloween 🎃 (default)
#   off        — disable seasonal colours entirely
# Note: seasonal-colours = false is equivalent to seasonal-calendar = "off"
# seasonal-calendar = "western"

# Colour the row-index column with the seasonal palette.
# colour-index = true


# -----------------------------------------------------------------------------
# Legendary PRs ⚔️
# Surface PRs that have become a team institution.
# A PR is legendary when it has 100+ total comments AND has been open 30+ days.
# -----------------------------------------------------------------------------

# Append ⚔️ to the State column of legendary PRs so they stand out at a glance.
# Equivalent to: --legendary
# legendary = false

# Show ONLY legendary PRs, hiding everything else. Implies legendary = true.
# Equivalent to: --legendary-only
# legendary-only = false


# -----------------------------------------------------------------------------
# Caching
# Cache results on disk so repeated runs are near-instant.
# The cache is keyed by (owner, repo-filter) — each pair gets its own
# file stored in ~/.cache/breakfast/ (or $XDG_CACHE_HOME/breakfast/).
# -----------------------------------------------------------------------------

# Enable the disk cache. Off by default.
# Use --refresh or --refresh-prs on a cached run to force a fresh fetch.
# Equivalent to: --cache
# cache = false

# How long cached results stay fresh before the next run fetches again.
# Accepts seconds (e.g. 300) or a human-friendly suffix: 30s, 5m, 2h.
# Only relevant when cache = true.
# Equivalent to: --cache-ttl <value>
# cache-ttl = "5m"

# Exclude draft PRs from results
# no-drafts = true


# -----------------------------------------------------------------------------
# Performance
# Control how aggressively breakfast fetches data in parallel.
# -----------------------------------------------------------------------------

# Number of parallel workers used to fetch PR details, check statuses, and
# approval statuses. Higher values fetch faster but consume more API rate limit.
# Equivalent to: --workers <n>
# workers = 64


# -----------------------------------------------------------------------------
# Diagnostics
# Tools for understanding what breakfast is doing under the hood.
# -----------------------------------------------------------------------------

# Print API diagnostics to stderr after output: total elapsed time, number of
# REST and GraphQL calls made, and rate-limit remaining/reset info.
# Equivalent to: --api-stats
# api-stats = false

# Disable all ANSI colour codes in output. Equivalent to setting the
# NO_COLOR environment variable (https://no-color.org/).
# Equivalent to: --no-colour
# no-colour = false


# -----------------------------------------------------------------------------
# Summary views
# Alternative output modes that replace the PR table with a compact summary.
# -----------------------------------------------------------------------------

# Instead of the table, print a summary grouped by PR author: count,
# oldest PR age, and total comments per person.
# Equivalent to: --summarise-user-prs
# summarise-user-prs = false

# Instead of the table, print a summary grouped by repository: count,
# oldest PR age, and total comments per repo.
# Equivalent to: --summarise-repo-prs
# summarise-repo-prs = false


# -----------------------------------------------------------------------------
# Update notifications
# Control how version update alerts appear.
# -----------------------------------------------------------------------------

# When a newer version of breakfast is available, include a short summary of
# what's new (pulled from the GitHub release notes) below the update banner.
# Equivalent to: --update-summary
# update-summary = false


# -----------------------------------------------------------------------------
# Sorting
# Control how the PR list is ordered.
# -----------------------------------------------------------------------------

# Sort PRs by field. Choices: repo (default), age, updated, author, comments, reviews.
# Equivalent to: --sort <field>
# sort = "repo"

# Reverse the sort order.
# Equivalent to: --reverse
# sort-reverse = false
"""


def _extract_option_blocks(content: str) -> list[tuple[str, str]]:
    """Parse a config template into (key, block_text) pairs.

    Each block_text is the run of comment lines leading up to (and including)
    the option definition line ``# key = default_value``.  Section separators
    (``# ---...`` / ``# ===...``) and blank lines delimit blocks.
    """
    lines = content.splitlines(keepends=True)
    results: list[tuple[str, str]] = []
    block_start: int | None = None

    for i, line in enumerate(lines):
        bare = line.rstrip("\n").strip()

        # Blank lines and section separators reset the current block accumulator
        if bare == "" or re.match(r"^# [-=]{5,}", bare):
            block_start = None
            continue

        if bare.startswith("#"):
            if block_start is None:
                block_start = i
            # Option definition line: # key = default
            m = re.match(r"^# ([a-z][a-z0-9-]+) =", bare)
            if m:
                key = m.group(1)
                block_text = "".join(lines[block_start : i + 1]).rstrip()
                results.append((key, block_text))
                block_start = None

    return results


def _key_present_in_file(key: str, content: str) -> bool:
    """Return True if *key* appears in *content* as an active or commented option."""
    pattern = rf"^#?\s*{re.escape(key)}\s*="
    return bool(re.search(pattern, content, re.MULTILINE))


_LIST_KEYS = {"ignore-author", "exclude-repos"}

_VALID_COLUMN_NAMES = frozenset(
    {
        "org",
        "repo",
        "title",
        "author",
        "state",
        "files",
        "commits",
        "diff",
        "comments",
        "age",
        "checks",
        "approvals",
        "head-branch",
        "base-branch",
        "reviewers",
        "labels",
        "mergeable",
        "link",
    }
)

_VALID_ALIGNMENTS = frozenset({"left", "center", "right"})


def parse_columns_config(columns_raw):
    """Parse the ``columns`` config value into a list of column spec dicts.

    Accepts either a plain list of column-name strings or a list of inline TOML
    tables with ``name``, optional ``header``, and optional ``align`` keys.

    Returns ``None`` when *columns_raw* is falsy (no custom column config).
    Returns a list of ``{"name": str, "header": str|None, "align": str|None}``
    dicts preserving the user's requested order.
    """
    if not columns_raw:
        return None

    specs = []
    for item in columns_raw:
        if isinstance(item, str):
            name = item.lower()
            if name not in _VALID_COLUMN_NAMES:
                click.echo(
                    click.style(
                        f"Warning: unknown column name '{name}' in config — skipping.",
                        fg="yellow",
                    ),
                    err=True,
                )
                continue
            specs.append({"name": name, "header": None, "align": None})
        elif isinstance(item, dict):
            name = str(item.get("name", "")).lower()
            if not name or name not in _VALID_COLUMN_NAMES:
                click.echo(
                    click.style(
                        f"Warning: unknown or missing column name '{name}'"
                        " in config — skipping.",
                        fg="yellow",
                    ),
                    err=True,
                )
                continue
            header = item.get("header") or None
            raw_align = item.get("align")
            if raw_align is not None:
                align = str(raw_align).lower()
                if align not in _VALID_ALIGNMENTS:
                    click.echo(
                        click.style(
                            f"Warning: invalid align '{raw_align}' for column"
                            f" '{name}' — must be left, center, or right."
                            " Ignoring.",
                            fg="yellow",
                        ),
                        err=True,
                    )
                    align = None
            else:
                align = None
            specs.append({"name": name, "header": header, "align": align})
        else:
            click.echo(
                click.style(
                    f"Warning: invalid columns entry {item!r} in config — skipping.",
                    fg="yellow",
                ),
                err=True,
            )

    return specs or None


def load_config(config_path=None):
    if config_path:
        paths = [Path(config_path).expanduser().resolve()]
    else:
        paths = get_config_paths()

    merged = {}
    for path in reversed(paths):
        if path.exists():
            with open(path, "rb") as f:
                try:
                    data = tomllib.load(f)
                except tomllib.TOMLDecodeError as e:
                    logger.warning("config_parse_error path=%s error=%r", path, str(e))
                    msg = f"Warning: Failed to parse config {path}: {e}"
                    click.echo(click.style(msg, fg="yellow"), err=True)
                    continue
            # seasonal-colours = false → seasonal-calendar = "off" (backward compat)
            if not data.get("seasonal-colours", True):
                data.setdefault("seasonal-calendar", "off")
            # organization → owner (deprecated key, backward compat)
            if "organization" in data:
                click.echo(
                    click.style(
                        "⚠️  Config key 'organization' is deprecated and will be"
                        " removed in a future release. Rename it to 'owner'.",
                        fg="yellow",
                    ),
                    err=True,
                )
                data.setdefault("owner", data.pop("organization"))
            for key in _LIST_KEYS:
                if key in data and not isinstance(data[key], list):
                    logger.warning(
                        "config_scalar_for_list_key path=%s key=%s value=%r",
                        path,
                        key,
                        data[key],
                    )
                    click.echo(
                        click.style(
                            f"Warning: config key '{key}' should be a list "
                            f'(e.g. ["{data[key]}"]), wrapping scalar automatically.',
                            fg="yellow",
                        ),
                        err=True,
                    )
                    data[key] = [data[key]]
            for key, value in data.items():
                if isinstance(value, list) and isinstance(merged.get(key), list):
                    merged[key] = value + merged[key]
                else:
                    merged[key] = value
    return merged


def generate_default_config():
    """Generate a default XDG-compliant config file."""
    config_dir = get_config_dir()
    config_path = config_dir / "config.toml"
    if config_path.exists():
        click.echo(
            click.style(f"Config file already exists at {config_path}", fg="yellow")
        )
        return False

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(_DEFAULT_CONFIG_CONTENT)
    click.echo(click.style(f"Created default config at {config_path}", fg="green"))
    return True


def update_config():
    """Append any missing options to the existing config file.

    Resolves the config file using the same priority order as load_config().
    Creates a timestamped backup before making any changes.  Returns True on
    success (including when already up to date) and False on error.
    """
    existing_path = None
    for path in get_config_paths():
        if path.exists():
            existing_path = path
            break

    if existing_path is None:
        click.echo(
            click.style(
                "No config file found. Run breakfast --init-config to create one.",
                fg="red",
                bold=True,
            )
        )
        return False

    click.echo(f"📋 Updating config at {existing_path}")

    try:
        existing_content = existing_path.read_text()
    except OSError as exc:
        click.echo(click.style(f"Error reading config: {exc}", fg="red", bold=True))
        return False

    option_blocks = _extract_option_blocks(_DEFAULT_CONFIG_CONTENT)
    missing = [
        (key, block)
        for key, block in option_blocks
        if not _key_present_in_file(key, existing_content)
    ]

    if not missing:
        click.echo(click.style("✅ Config is already up to date.", fg="green"))
        return True

    # Write timestamped backup before touching the file
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_path = existing_path.parent / (existing_path.name + f".bak.{timestamp}")
    try:
        backup_path.write_text(existing_content)
    except OSError as exc:
        click.echo(click.style(f"Error writing backup: {exc}", fg="red", bold=True))
        return False
    click.echo(f"💾 Backup saved to {backup_path}")

    # Append missing option blocks
    new_content = existing_content
    if not new_content.endswith("\n"):
        new_content += "\n"
    try:
        _version = pkg_version("breakfast")
    except PackageNotFoundError:
        _version = "unknown"
    readable_ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    separator = (
        f"# --- Added by --update-config (breakfast v{_version}) on {readable_ts} ---"
    )
    new_content += f"\n{separator}\n"
    for _key, block in missing:
        new_content += f"\n{block}\n"

    try:
        existing_path.write_text(new_content)
    except OSError as exc:
        click.echo(click.style(f"Error writing config: {exc}", fg="red", bold=True))
        return False

    click.echo(click.style(f"✅ Added {len(missing)} missing option(s):", fg="green"))
    for key, _ in missing:
        click.echo(f"   {key}")

    return True


def normalize_ignore_authors(ignore_authors):
    if not ignore_authors:
        return set()
    return {
        author.strip().lower() for author in ignore_authors if author and author.strip()
    }


def filter_pr_details(
    pr_details,
    ignore_authors,
    mine_only=False,
    current_user_login=None,
    no_drafts=False,
    drafts_only=False,
    filter_state=None,
    filter_check=None,
    filter_approval=None,
    filter_mergeable=None,
    check_statuses=None,
    approval_statuses=None,
    search_title=None,
    filter_reviewer=None,
    filter_label=None,
    exclude_label=None,
    filter_stale=None,
    filter_inactive=None,
):
    ignore_set = normalize_ignore_authors(ignore_authors)
    current_user_login_normalized = (
        current_user_login.lower()
        if mine_only and current_user_login and current_user_login.strip()
        else None
    )
    filtered = []
    for pr_detail in pr_details:
        author_login = pr_detail.get("user", {}).get("login", "")
        author_login_normalized = author_login.lower()

        if author_login_normalized in ignore_set:
            continue
        if (
            current_user_login_normalized
            and author_login_normalized != current_user_login_normalized
        ):
            continue
        is_draft = pr_detail.get("draft", False)
        if no_drafts and is_draft:
            continue
        if drafts_only and not is_draft:
            continue
        if filter_state:
            filter_state_lower = {s.lower() for s in filter_state}
            regular_states = filter_state_lower - {"draft"}
            include_drafts = "draft" in filter_state_lower
            is_draft = pr_detail.get("draft", False)
            pr_state = pr_detail.get("state", "").lower()
            state_match = bool(regular_states) and pr_state in regular_states
            draft_match = include_drafts and is_draft
            if not (state_match or draft_match):
                continue
        if filter_check and check_statuses is not None:
            pr_check = check_statuses.get(pr_detail["id"], "none")
            if pr_check not in filter_check:
                continue
        if filter_approval and approval_statuses is not None:
            pr_approval = approval_statuses.get(pr_detail["id"], "pending")
            if pr_approval not in filter_approval:
                continue
        if filter_mergeable:
            raw = pr_detail.get("mergeable")
            if raw is True:
                mergeable_status = "clean"
            elif raw is False:
                mergeable_status = "conflict"
            else:
                mergeable_status = "unknown"
            if mergeable_status not in filter_mergeable:
                continue
        if search_title is not None:
            title = pr_detail.get("title", "")
            if not re.search(search_title, title, re.IGNORECASE):
                continue
        if filter_reviewer:
            reviewers = {
                r["login"].lower() for r in pr_detail.get("requested_reviewers", [])
            }
            if not any(rv.lower() in reviewers for rv in filter_reviewer):
                continue
        if filter_label:
            pr_labels = {lb["name"].lower() for lb in pr_detail.get("labels", [])}
            if not any(lbl.lower() in pr_labels for lbl in filter_label):
                continue
        if exclude_label:
            pr_labels = {lb["name"].lower() for lb in pr_detail.get("labels", [])}
            if any(lbl.lower() in pr_labels for lbl in exclude_label):
                continue
        if filter_stale is not None and get_pr_age_days(pr_detail) < filter_stale:
            continue
        if filter_inactive is not None:
            if get_pr_inactive_days(pr_detail) < filter_inactive:
                continue

        filtered.append(pr_detail)
    return filtered
