import re
import tomllib
from datetime import datetime
from pathlib import Path

import click

from .logger import logger
from .xdg import get_config_dir

_DEFAULT_CONFIG_CONTENT = """\
# =============================================================================
#  breakfast configuration file
#  Generated by: breakfast --init-config
#
#  All options are commented out — uncomment and edit to activate.
#  Options set here act as persistent defaults; CLI flags always take
#  precedence over config file values for a single run.
#
#  Config file locations (highest → lowest priority):
#    ./.breakfast.toml            (current directory)
#    ~/.config/breakfast/config.toml   (XDG default, this file)
#    ~/.breakfast.toml
# =============================================================================


# -----------------------------------------------------------------------------
# Target
# Which organisation and repos to query by default.
# -----------------------------------------------------------------------------

# GitHub organisation to query for open pull requests.
# Equivalent to: breakfast -o <value>
# Required (must be set here or passed with -o on every run).
# organization = "my-org"

# Filter repositories by name substring. Only repos whose name contains
# this string are included. An empty string matches all repos.
# Equivalent to: breakfast -r <value>
# repo-filter = "my-app"


# -----------------------------------------------------------------------------
# Filtering
# Control which PRs appear in the output.
# -----------------------------------------------------------------------------

# Authors to exclude from the output (case-insensitive). Useful for hiding
# bot PRs. List format — add as many entries as you like.
# Equivalent to: --ignore-author dependabot[bot] --ignore-author renovate[bot]
# ignore-author = ["dependabot[bot]", "renovate[bot]"]

# Show only PRs authored by the currently authenticated GitHub user
# (determined from GITHUB_TOKEN). Useful for a personal morning view.
# Equivalent to: --mine-only
# mine-only = false

# Maximum number of PRs to display. Applied after all other filters.
# Unset means show all results.
# Equivalent to: --limit <n>
# limit = 25


# -----------------------------------------------------------------------------
# Columns
# Toggle and configure optional table columns.
# -----------------------------------------------------------------------------

# Show a column with the PR age in days (time since it was opened).
# Values are colour-coded: green < 10d, yellow < 20d, orange < 50d, red 50d+.
# Equivalent to: --age
# age = false

# Show a column with the CI/check status for each PR. Requires an extra
# API call per PR so is opt-in. Values: pass, fail, pending, none.
# Equivalent to: --checks
# checks = false

# Show a column with the review approval status for each PR. Requires an
# extra API call per PR so is opt-in. Values: approved, pending, changes.
# Equivalent to: --approvals
# approvals = false

# Truncate PR titles to this many characters (appends … when truncated).
# Useful on narrow terminals. Unset means no truncation.
# Equivalent to: --max-title-length <n>
# max-title-length = 72


# -----------------------------------------------------------------------------
# Display
# Control how the output looks.
# -----------------------------------------------------------------------------

# Output format. "table" renders a coloured terminal table (default).
# "json" outputs machine-readable JSON — useful for scripting or piping.
# Equivalent to: --json
# format = "table"

# How status columns (Checks, Approved, Mergeable?) are rendered.
#   emoji  — colourful emoji labels, e.g. ✅ pass, ❌ fail  (default)
#   ascii  — plain text fallback, e.g. pass, fail — safe for all terminals
# Equivalent to: --status-style emoji|ascii
# status-style = "emoji"


# -----------------------------------------------------------------------------
# Legendary PRs ⚔️
# Surface PRs that have become a team institution.
# A PR is legendary when it has 100+ total comments AND has been open 30+ days.
# -----------------------------------------------------------------------------

# Append ⚔️ to the State column of legendary PRs so they stand out at a glance.
# Equivalent to: --legendary
# legendary = false

# Show ONLY legendary PRs, hiding everything else. Implies legendary = true.
# Equivalent to: --legendary-only
# legendary-only = false


# -----------------------------------------------------------------------------
# Caching
# Cache results on disk so repeated runs are near-instant.
# The cache is keyed by (organization, repo-filter) — each pair gets its own
# file stored in ~/.cache/breakfast/ (or $XDG_CACHE_HOME/breakfast/).
# -----------------------------------------------------------------------------

# Enable the disk cache. Off by default.
# Use --refresh or --refresh-prs on a cached run to force a fresh fetch.
# Equivalent to: --cache
# cache = false

# How long cached results stay fresh before the next run fetches again.
# Accepts seconds (e.g. 300) or a human-friendly suffix: 30s, 5m, 2h.
# Only relevant when cache = true.
# Equivalent to: --cache-ttl <value>
# cache-ttl = "5m"

# Exclude draft PRs from results
# no-drafts = true


# -----------------------------------------------------------------------------
# Performance
# Control how aggressively breakfast fetches data in parallel.
# -----------------------------------------------------------------------------

# Number of parallel workers used to fetch PR details, check statuses, and
# approval statuses. Higher values fetch faster but consume more API rate limit.
# Equivalent to: --workers <n>
# workers = 64


# -----------------------------------------------------------------------------
# Diagnostics
# Tools for understanding what breakfast is doing under the hood.
# -----------------------------------------------------------------------------

# Print API diagnostics to stderr after output: total elapsed time, number of
# REST and GraphQL calls made, and rate-limit remaining/reset info.
# Equivalent to: --api-stats
# api-stats = false

# Disable all ANSI colour codes in output. Equivalent to setting the
# NO_COLOR environment variable (https://no-color.org/).
# Equivalent to: --no-colour
# no-colour = false
"""


def _extract_option_blocks(content: str) -> list[tuple[str, str]]:
    """Parse a config template into (key, block_text) pairs.

    Each block_text is the run of comment lines leading up to (and including)
    the option definition line ``# key = default_value``.  Section separators
    (``# ---...`` / ``# ===...``) and blank lines delimit blocks.
    """
    lines = content.splitlines(keepends=True)
    results: list[tuple[str, str]] = []
    block_start: int | None = None

    for i, line in enumerate(lines):
        bare = line.rstrip("\n").strip()

        # Blank lines and section separators reset the current block accumulator
        if bare == "" or re.match(r"^# [-=]{5,}", bare):
            block_start = None
            continue

        if bare.startswith("#"):
            if block_start is None:
                block_start = i
            # Option definition line: # key = default
            m = re.match(r"^# ([a-z][a-z0-9-]+) =", bare)
            if m:
                key = m.group(1)
                block_text = "".join(lines[block_start : i + 1]).rstrip()
                results.append((key, block_text))
                block_start = None

    return results


def _key_present_in_file(key: str, content: str) -> bool:
    """Return True if *key* appears in *content* as an active or commented option."""
    pattern = rf"^#?\s*{re.escape(key)}\s*="
    return bool(re.search(pattern, content, re.MULTILINE))


def load_config(config_path=None):
    if config_path:
        paths = [Path(config_path).expanduser().resolve()]
    else:
        # XDG-compliant pathing prioritized
        config_dir = get_config_dir()
        paths = [
            Path.cwd() / ".breakfast.toml",
            config_dir / "config.toml",
            Path.home() / ".breakfast.toml",
        ]

    merged = {}
    for path in reversed(paths):
        if path.exists():
            with open(path, "rb") as f:
                try:
                    data = tomllib.load(f)
                except Exception as e:
                    logger.warning("config_parse_error path=%s error=%r", path, str(e))
                    msg = f"Warning: Failed to parse config {path}: {e}"
                    click.echo(click.style(msg, fg="yellow"), err=True)
                    continue
            for key, value in data.items():
                if isinstance(value, list) and isinstance(merged.get(key), list):
                    merged[key] = value + merged[key]
                else:
                    merged[key] = value
    return merged


def generate_default_config():
    """Generate a default XDG-compliant config file."""
    config_dir = get_config_dir()
    config_path = config_dir / "config.toml"
    if config_path.exists():
        click.echo(
            click.style(f"Config file already exists at {config_path}", fg="yellow")
        )
        return False

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(_DEFAULT_CONFIG_CONTENT)
    click.echo(click.style(f"Created default config at {config_path}", fg="green"))
    return True


def update_config():
    """Append any missing options to the existing config file.

    Resolves the config file using the same priority order as load_config().
    Creates a timestamped backup before making any changes.  Returns True on
    success (including when already up to date) and False on error.
    """
    config_dir = get_config_dir()
    paths = [
        Path.cwd() / ".breakfast.toml",
        config_dir / "config.toml",
        Path.home() / ".breakfast.toml",
    ]

    existing_path = None
    for path in paths:
        if path.exists():
            existing_path = path
            break

    if existing_path is None:
        click.echo(
            click.style(
                "No config file found. Run breakfast --init-config to create one.",
                fg="red",
                bold=True,
            )
        )
        return False

    click.echo(f"📋 Updating config at {existing_path}")

    try:
        existing_content = existing_path.read_text()
    except OSError as exc:
        click.echo(click.style(f"Error reading config: {exc}", fg="red", bold=True))
        return False

    option_blocks = _extract_option_blocks(_DEFAULT_CONFIG_CONTENT)
    missing = [
        (key, block)
        for key, block in option_blocks
        if not _key_present_in_file(key, existing_content)
    ]

    if not missing:
        click.echo(click.style("✅ Config is already up to date.", fg="green"))
        return True

    # Write timestamped backup before touching the file
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup_path = existing_path.parent / (existing_path.name + f".bak.{timestamp}")
    try:
        backup_path.write_text(existing_content)
    except OSError as exc:
        click.echo(click.style(f"Error writing backup: {exc}", fg="red", bold=True))
        return False
    click.echo(f"💾 Backup saved to {backup_path}")

    # Append missing option blocks
    new_content = existing_content
    if not new_content.endswith("\n"):
        new_content += "\n"
    new_content += "\n# --- Added by --update-config ---\n"
    for _key, block in missing:
        new_content += f"\n{block}\n"

    try:
        existing_path.write_text(new_content)
    except OSError as exc:
        click.echo(click.style(f"Error writing config: {exc}", fg="red", bold=True))
        return False

    click.echo(click.style(f"✅ Added {len(missing)} missing option(s):", fg="green"))
    for key, _ in missing:
        click.echo(f"   {key}")

    return True


def normalize_ignore_authors(ignore_authors):
    if not ignore_authors:
        return set()
    return {
        author.strip().lower() for author in ignore_authors if author and author.strip()
    }


def filter_pr_details(
    pr_details,
    ignore_authors,
    mine_only=False,
    current_user_login=None,
    no_drafts=False,
    drafts_only=False,
    filter_state=None,
    filter_check=None,
    filter_approval=None,
    check_statuses=None,
    approval_statuses=None,
    search_title=None,
):
    ignore_set = normalize_ignore_authors(ignore_authors)
    current_user_login_normalized = (
        current_user_login.lower()
        if mine_only and current_user_login and current_user_login.strip()
        else None
    )
    filtered = []
    for pr_detail in pr_details:
        author_login = pr_detail.get("user", {}).get("login", "")
        author_login_normalized = author_login.lower()

        if author_login_normalized in ignore_set:
            continue
        if (
            current_user_login_normalized
            and author_login_normalized != current_user_login_normalized
        ):
            continue
        is_draft = pr_detail.get("draft", False)
        if no_drafts and is_draft:
            continue
        if drafts_only and not is_draft:
            continue
        if filter_state:
            filter_state_lower = {s.lower() for s in filter_state}
            regular_states = filter_state_lower - {"draft"}
            include_drafts = "draft" in filter_state_lower
            is_draft = pr_detail.get("draft", False)
            pr_state = pr_detail.get("state", "").lower()
            state_match = bool(regular_states) and pr_state in regular_states
            draft_match = include_drafts and is_draft
            if not (state_match or draft_match):
                continue
        if filter_check and check_statuses is not None:
            pr_check = check_statuses.get(pr_detail["id"], "none")
            if pr_check not in filter_check:
                continue
        if filter_approval and approval_statuses is not None:
            pr_approval = approval_statuses.get(pr_detail["id"], "pending")
            if pr_approval not in filter_approval:
                continue
        if search_title is not None:
            title = pr_detail.get("title", "")
            if not re.search(search_title, title, re.IGNORECASE):
                continue

        filtered.append(pr_detail)
    return filtered
